// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Jimdo/wonderland-crons/aws (interfaces: CronExecutionStore)

// Package mock is a generated GoMock package.
package mock

import (
	cron "github.com/Jimdo/wonderland-crons/cron"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockCronExecutionStore is a mock of CronExecutionStore interface
type MockCronExecutionStore struct {
	ctrl     *gomock.Controller
	recorder *MockCronExecutionStoreMockRecorder
}

// MockCronExecutionStoreMockRecorder is the mock recorder for MockCronExecutionStore
type MockCronExecutionStoreMockRecorder struct {
	mock *MockCronExecutionStore
}

// NewMockCronExecutionStore creates a new mock instance
func NewMockCronExecutionStore(ctrl *gomock.Controller) *MockCronExecutionStore {
	mock := &MockCronExecutionStore{ctrl: ctrl}
	mock.recorder = &MockCronExecutionStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockCronExecutionStore) EXPECT() *MockCronExecutionStoreMockRecorder {
	return m.recorder
}

// Delete mocks base method
func (m *MockCronExecutionStore) Delete(arg0 string) error {
	ret := m.ctrl.Call(m, "Delete", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete
func (mr *MockCronExecutionStoreMockRecorder) Delete(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockCronExecutionStore)(nil).Delete), arg0)
}

// GetLastNExecutions mocks base method
func (m *MockCronExecutionStore) GetLastNExecutions(arg0 string, arg1 int64) ([]*cron.Execution, error) {
	ret := m.ctrl.Call(m, "GetLastNExecutions", arg0, arg1)
	ret0, _ := ret[0].([]*cron.Execution)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLastNExecutions indicates an expected call of GetLastNExecutions
func (mr *MockCronExecutionStoreMockRecorder) GetLastNExecutions(arg0, arg1 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLastNExecutions", reflect.TypeOf((*MockCronExecutionStore)(nil).GetLastNExecutions), arg0, arg1)
}
