// Automatically generated by MockGen. DO NOT EDIT!
// Source: github.com/Jimdo/wonderland-crons/aws (interfaces: CronExecutionStore)

package mock

import (
	store "github.com/Jimdo/wonderland-crons/store"
	gomock "github.com/golang/mock/gomock"
)

// Mock of CronExecutionStore interface
type MockCronExecutionStore struct {
	ctrl     *gomock.Controller
	recorder *_MockCronExecutionStoreRecorder
}

// Recorder for MockCronExecutionStore (not exported)
type _MockCronExecutionStoreRecorder struct {
	mock *MockCronExecutionStore
}

func NewMockCronExecutionStore(ctrl *gomock.Controller) *MockCronExecutionStore {
	mock := &MockCronExecutionStore{ctrl: ctrl}
	mock.recorder = &_MockCronExecutionStoreRecorder{mock}
	return mock
}

func (_m *MockCronExecutionStore) EXPECT() *_MockCronExecutionStoreRecorder {
	return _m.recorder
}

func (_m *MockCronExecutionStore) GetLastNExecutions(_param0 string, _param1 int64) ([]*store.Execution, error) {
	ret := _m.ctrl.Call(_m, "GetLastNExecutions", _param0, _param1)
	ret0, _ := ret[0].([]*store.Execution)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockCronExecutionStoreRecorder) GetLastNExecutions(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "GetLastNExecutions", arg0, arg1)
}
