// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Jimdo/wonderland-crons/aws (interfaces: CronValidator)

// Package mock is a generated GoMock package.
package mock

import (
	cron "github.com/Jimdo/wonderland-crons/cron"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockCronValidator is a mock of CronValidator interface
type MockCronValidator struct {
	ctrl     *gomock.Controller
	recorder *MockCronValidatorMockRecorder
}

// MockCronValidatorMockRecorder is the mock recorder for MockCronValidator
type MockCronValidatorMockRecorder struct {
	mock *MockCronValidator
}

// NewMockCronValidator creates a new mock instance
func NewMockCronValidator(ctrl *gomock.Controller) *MockCronValidator {
	mock := &MockCronValidator{ctrl: ctrl}
	mock.recorder = &MockCronValidatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockCronValidator) EXPECT() *MockCronValidatorMockRecorder {
	return m.recorder
}

// ValidateCronDescription mocks base method
func (m *MockCronValidator) ValidateCronDescription(arg0 *cron.Description) error {
	ret := m.ctrl.Call(m, "ValidateCronDescription", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// ValidateCronDescription indicates an expected call of ValidateCronDescription
func (mr *MockCronValidatorMockRecorder) ValidateCronDescription(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateCronDescription", reflect.TypeOf((*MockCronValidator)(nil).ValidateCronDescription), arg0)
}

// ValidateCronName mocks base method
func (m *MockCronValidator) ValidateCronName(arg0 string) error {
	ret := m.ctrl.Call(m, "ValidateCronName", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// ValidateCronName indicates an expected call of ValidateCronName
func (mr *MockCronValidatorMockRecorder) ValidateCronName(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateCronName", reflect.TypeOf((*MockCronValidator)(nil).ValidateCronName), arg0)
}
