// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Jimdo/wonderland-crons/cronitor (interfaces: CronitorAPI)

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	cronitor "github.com/Jimdo/wonderland-crons/cronitor"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockCronitorAPI is a mock of CronitorAPI interface
type MockCronitorAPI struct {
	ctrl     *gomock.Controller
	recorder *MockCronitorAPIMockRecorder
}

// MockCronitorAPIMockRecorder is the mock recorder for MockCronitorAPI
type MockCronitorAPIMockRecorder struct {
	mock *MockCronitorAPI
}

// NewMockCronitorAPI creates a new mock instance
func NewMockCronitorAPI(ctrl *gomock.Controller) *MockCronitorAPI {
	mock := &MockCronitorAPI{ctrl: ctrl}
	mock.recorder = &MockCronitorAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockCronitorAPI) EXPECT() *MockCronitorAPIMockRecorder {
	return m.recorder
}

// CreateOrUpdate mocks base method
func (m *MockCronitorAPI) CreateOrUpdate(arg0 context.Context, arg1 cronitor.CreateOrUpdateParams) error {
	ret := m.ctrl.Call(m, "CreateOrUpdate", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateOrUpdate indicates an expected call of CreateOrUpdate
func (mr *MockCronitorAPIMockRecorder) CreateOrUpdate(arg0, arg1 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOrUpdate", reflect.TypeOf((*MockCronitorAPI)(nil).CreateOrUpdate), arg0, arg1)
}

// Delete mocks base method
func (m *MockCronitorAPI) Delete(arg0 context.Context, arg1 string) error {
	ret := m.ctrl.Call(m, "Delete", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete
func (mr *MockCronitorAPIMockRecorder) Delete(arg0, arg1 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockCronitorAPI)(nil).Delete), arg0, arg1)
}
