// Automatically generated by MockGen. DO NOT EDIT!
// Source: github.com/Jimdo/wonderland-crons/aws (interfaces: CronTaskStore)

package mock

import (
	store "github.com/Jimdo/wonderland-crons/store"
	gomock "github.com/golang/mock/gomock"
)

// Mock of CronTaskStore interface
type MockCronTaskStore struct {
	ctrl     *gomock.Controller
	recorder *_MockCronTaskStoreRecorder
}

// Recorder for MockCronTaskStore (not exported)
type _MockCronTaskStoreRecorder struct {
	mock *MockCronTaskStore
}

func NewMockCronTaskStore(ctrl *gomock.Controller) *MockCronTaskStore {
	mock := &MockCronTaskStore{ctrl: ctrl}
	mock.recorder = &_MockCronTaskStoreRecorder{mock}
	return mock
}

func (_m *MockCronTaskStore) EXPECT() *_MockCronTaskStoreRecorder {
	return _m.recorder
}

func (_m *MockCronTaskStore) GetLastNTaskExecutions(_param0 string, _param1 int64) ([]*store.Execution, error) {
	ret := _m.ctrl.Call(_m, "GetLastNTaskExecutions", _param0, _param1)
	ret0, _ := ret[0].([]*store.Execution)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockCronTaskStoreRecorder) GetLastNTaskExecutions(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "GetLastNTaskExecutions", arg0, arg1)
}
