// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Jimdo/wonderland-crons/events (interfaces: CronStateToggler)

// Package mock is a generated GoMock package.
package mock

import (
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockCronStateToggler is a mock of CronStateToggler interface
type MockCronStateToggler struct {
	ctrl     *gomock.Controller
	recorder *MockCronStateTogglerMockRecorder
}

// MockCronStateTogglerMockRecorder is the mock recorder for MockCronStateToggler
type MockCronStateTogglerMockRecorder struct {
	mock *MockCronStateToggler
}

// NewMockCronStateToggler creates a new mock instance
func NewMockCronStateToggler(ctrl *gomock.Controller) *MockCronStateToggler {
	mock := &MockCronStateToggler{ctrl: ctrl}
	mock.recorder = &MockCronStateTogglerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockCronStateToggler) EXPECT() *MockCronStateTogglerMockRecorder {
	return m.recorder
}

// Activate mocks base method
func (m *MockCronStateToggler) Activate(arg0 string) error {
	ret := m.ctrl.Call(m, "Activate", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Activate indicates an expected call of Activate
func (mr *MockCronStateTogglerMockRecorder) Activate(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Activate", reflect.TypeOf((*MockCronStateToggler)(nil).Activate), arg0)
}

// Deactivate mocks base method
func (m *MockCronStateToggler) Deactivate(arg0 string) error {
	ret := m.ctrl.Call(m, "Deactivate", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Deactivate indicates an expected call of Deactivate
func (mr *MockCronStateTogglerMockRecorder) Deactivate(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Deactivate", reflect.TypeOf((*MockCronStateToggler)(nil).Deactivate), arg0)
}
