// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Jimdo/wonderland-crons/metrics (interfaces: Updater)

// Package mock is a generated GoMock package.
package mock

import (
	cron "github.com/Jimdo/wonderland-crons/cron"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockUpdater is a mock of Updater interface
type MockUpdater struct {
	ctrl     *gomock.Controller
	recorder *MockUpdaterMockRecorder
}

// MockUpdaterMockRecorder is the mock recorder for MockUpdater
type MockUpdaterMockRecorder struct {
	mock *MockUpdater
}

// NewMockUpdater creates a new mock instance
func NewMockUpdater(ctrl *gomock.Controller) *MockUpdater {
	mock := &MockUpdater{ctrl: ctrl}
	mock.recorder = &MockUpdaterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockUpdater) EXPECT() *MockUpdaterMockRecorder {
	return m.recorder
}

// IncExecutionFinishedCounter mocks base method
func (m *MockUpdater) IncExecutionFinishedCounter(arg0 *cron.Cron, arg1 string) {
	m.ctrl.Call(m, "IncExecutionFinishedCounter", arg0, arg1)
}

// IncExecutionFinishedCounter indicates an expected call of IncExecutionFinishedCounter
func (mr *MockUpdaterMockRecorder) IncExecutionFinishedCounter(arg0, arg1 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncExecutionFinishedCounter", reflect.TypeOf((*MockUpdater)(nil).IncExecutionFinishedCounter), arg0, arg1)
}

// IncExecutionTriggeredCounter mocks base method
func (m *MockUpdater) IncExecutionTriggeredCounter(arg0 *cron.Cron, arg1 string) {
	m.ctrl.Call(m, "IncExecutionTriggeredCounter", arg0, arg1)
}

// IncExecutionTriggeredCounter indicates an expected call of IncExecutionTriggeredCounter
func (mr *MockUpdaterMockRecorder) IncExecutionTriggeredCounter(arg0, arg1 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncExecutionTriggeredCounter", reflect.TypeOf((*MockUpdater)(nil).IncExecutionTriggeredCounter), arg0, arg1)
}
