// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Jimdo/wonderland-crons/aws (interfaces: NotificationClient)

// Package mock is a generated GoMock package.
package mock

import (
	cron "github.com/Jimdo/wonderland-crons/cron"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockNotificationClient is a mock of NotificationClient interface
type MockNotificationClient struct {
	ctrl     *gomock.Controller
	recorder *MockNotificationClientMockRecorder
}

// MockNotificationClientMockRecorder is the mock recorder for MockNotificationClient
type MockNotificationClientMockRecorder struct {
	mock *MockNotificationClient
}

// NewMockNotificationClient creates a new mock instance
func NewMockNotificationClient(ctrl *gomock.Controller) *MockNotificationClient {
	mock := &MockNotificationClient{ctrl: ctrl}
	mock.recorder = &MockNotificationClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockNotificationClient) EXPECT() *MockNotificationClientMockRecorder {
	return m.recorder
}

// CreateOrUpdateNotificationChannel mocks base method
func (m *MockNotificationClient) CreateOrUpdateNotificationChannel(arg0 string, arg1 *cron.CronNotification) (string, string, error) {
	ret := m.ctrl.Call(m, "CreateOrUpdateNotificationChannel", arg0, arg1)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// CreateOrUpdateNotificationChannel indicates an expected call of CreateOrUpdateNotificationChannel
func (mr *MockNotificationClientMockRecorder) CreateOrUpdateNotificationChannel(arg0, arg1 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOrUpdateNotificationChannel", reflect.TypeOf((*MockNotificationClient)(nil).CreateOrUpdateNotificationChannel), arg0, arg1)
}

// DeleteNotificationChannel mocks base method
func (m *MockNotificationClient) DeleteNotificationChannel(arg0 string) error {
	ret := m.ctrl.Call(m, "DeleteNotificationChannel", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteNotificationChannel indicates an expected call of DeleteNotificationChannel
func (mr *MockNotificationClientMockRecorder) DeleteNotificationChannel(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteNotificationChannel", reflect.TypeOf((*MockNotificationClient)(nil).DeleteNotificationChannel), arg0)
}
