// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Jimdo/wonderland-crons/aws (interfaces: RuleCronManager)

// Package mock is a generated GoMock package.
package mock

import (
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockRuleCronManager is a mock of RuleCronManager interface
type MockRuleCronManager struct {
	ctrl     *gomock.Controller
	recorder *MockRuleCronManagerMockRecorder
}

// MockRuleCronManagerMockRecorder is the mock recorder for MockRuleCronManager
type MockRuleCronManagerMockRecorder struct {
	mock *MockRuleCronManager
}

// NewMockRuleCronManager creates a new mock instance
func NewMockRuleCronManager(ctrl *gomock.Controller) *MockRuleCronManager {
	mock := &MockRuleCronManager{ctrl: ctrl}
	mock.recorder = &MockRuleCronManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockRuleCronManager) EXPECT() *MockRuleCronManagerMockRecorder {
	return m.recorder
}

// ActivateRule mocks base method
func (m *MockRuleCronManager) ActivateRule(arg0 string) error {
	ret := m.ctrl.Call(m, "ActivateRule", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// ActivateRule indicates an expected call of ActivateRule
func (mr *MockRuleCronManagerMockRecorder) ActivateRule(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ActivateRule", reflect.TypeOf((*MockRuleCronManager)(nil).ActivateRule), arg0)
}

// DeactivateRule mocks base method
func (m *MockRuleCronManager) DeactivateRule(arg0 string) error {
	ret := m.ctrl.Call(m, "DeactivateRule", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeactivateRule indicates an expected call of DeactivateRule
func (mr *MockRuleCronManagerMockRecorder) DeactivateRule(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeactivateRule", reflect.TypeOf((*MockRuleCronManager)(nil).DeactivateRule), arg0)
}

// DeleteRule mocks base method
func (m *MockRuleCronManager) DeleteRule(arg0 string) error {
	ret := m.ctrl.Call(m, "DeleteRule", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteRule indicates an expected call of DeleteRule
func (mr *MockRuleCronManagerMockRecorder) DeleteRule(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRule", reflect.TypeOf((*MockRuleCronManager)(nil).DeleteRule), arg0)
}

// RunTaskDefinitionWithSchedule mocks base method
func (m *MockRuleCronManager) RunTaskDefinitionWithSchedule(arg0, arg1, arg2 string) (string, error) {
	ret := m.ctrl.Call(m, "RunTaskDefinitionWithSchedule", arg0, arg1, arg2)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RunTaskDefinitionWithSchedule indicates an expected call of RunTaskDefinitionWithSchedule
func (mr *MockRuleCronManagerMockRecorder) RunTaskDefinitionWithSchedule(arg0, arg1, arg2 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunTaskDefinitionWithSchedule", reflect.TypeOf((*MockRuleCronManager)(nil).RunTaskDefinitionWithSchedule), arg0, arg1, arg2)
}
