// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Jimdo/wonderland-crons/aws (interfaces: TaskDefinitionStore)

// Package mock is a generated GoMock package.
package mock

import (
	cron "github.com/Jimdo/wonderland-crons/cron"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockTaskDefinitionStore is a mock of TaskDefinitionStore interface
type MockTaskDefinitionStore struct {
	ctrl     *gomock.Controller
	recorder *MockTaskDefinitionStoreMockRecorder
}

// MockTaskDefinitionStoreMockRecorder is the mock recorder for MockTaskDefinitionStore
type MockTaskDefinitionStoreMockRecorder struct {
	mock *MockTaskDefinitionStore
}

// NewMockTaskDefinitionStore creates a new mock instance
func NewMockTaskDefinitionStore(ctrl *gomock.Controller) *MockTaskDefinitionStore {
	mock := &MockTaskDefinitionStore{ctrl: ctrl}
	mock.recorder = &MockTaskDefinitionStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockTaskDefinitionStore) EXPECT() *MockTaskDefinitionStoreMockRecorder {
	return m.recorder
}

// AddRevisionFromCronDescription mocks base method
func (m *MockTaskDefinitionStore) AddRevisionFromCronDescription(arg0, arg1 string, arg2 *cron.CronDescription) (string, error) {
	ret := m.ctrl.Call(m, "AddRevisionFromCronDescription", arg0, arg1, arg2)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddRevisionFromCronDescription indicates an expected call of AddRevisionFromCronDescription
func (mr *MockTaskDefinitionStoreMockRecorder) AddRevisionFromCronDescription(arg0, arg1, arg2 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddRevisionFromCronDescription", reflect.TypeOf((*MockTaskDefinitionStore)(nil).AddRevisionFromCronDescription), arg0, arg1, arg2)
}

// DeleteByFamily mocks base method
func (m *MockTaskDefinitionStore) DeleteByFamily(arg0 string) error {
	ret := m.ctrl.Call(m, "DeleteByFamily", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByFamily indicates an expected call of DeleteByFamily
func (mr *MockTaskDefinitionStoreMockRecorder) DeleteByFamily(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByFamily", reflect.TypeOf((*MockTaskDefinitionStore)(nil).DeleteByFamily), arg0)
}
