# vim: set syntax=dockerfile:
FROM golang:alpine

ENV CGO_ENABLED=0

RUN apk --update add ca-certificates

RUN set -ex \
    && apk add --update git \
    && go get -u gopkg.in/alecthomas/gometalinter.v1 \
    && gometalinter.v1 --install

WORKDIR /go/src/github.com/Jimdo/wonderland-crons

CMD ["./script/test"]
