// Automatically generated by MockGen. DO NOT EDIT!
// Source: github.com/Jimdo/wonderland-crons/aws (interfaces: CronStore)

package mock

import (
	gomock "github.com/golang/mock/gomock"
)

// Mock of CronStore interface
type MockCronStore struct {
	ctrl     *gomock.Controller
	recorder *_MockCronStoreRecorder
}

// Recorder for MockCronStore (not exported)
type _MockCronStoreRecorder struct {
	mock *MockCronStore
}

func NewMockCronStore(ctrl *gomock.Controller) *MockCronStore {
	mock := &MockCronStore{ctrl: ctrl}
	mock.recorder = &_MockCronStoreRecorder{mock}
	return mock
}

func (_m *MockCronStore) EXPECT() *_MockCronStoreRecorder {
	return _m.recorder
}
