// Automatically generated by MockGen. DO NOT EDIT!
// Source: github.com/Jimdo/wonderland-crons/aws (interfaces: CronValidator)

package mock

import (
	cron "github.com/Jimdo/wonderland-crons/cron"
	gomock "github.com/golang/mock/gomock"
)

// Mock of CronValidator interface
type MockCronValidator struct {
	ctrl     *gomock.Controller
	recorder *_MockCronValidatorRecorder
}

// Recorder for MockCronValidator (not exported)
type _MockCronValidatorRecorder struct {
	mock *MockCronValidator
}

func NewMockCronValidator(ctrl *gomock.Controller) *MockCronValidator {
	mock := &MockCronValidator{ctrl: ctrl}
	mock.recorder = &_MockCronValidatorRecorder{mock}
	return mock
}

func (_m *MockCronValidator) EXPECT() *_MockCronValidatorRecorder {
	return _m.recorder
}

func (_m *MockCronValidator) ValidateCronDescription(_param0 *cron.CronDescription) error {
	ret := _m.ctrl.Call(_m, "ValidateCronDescription", _param0)
	ret0, _ := ret[0].(error)
	return ret0
}

func (_mr *_MockCronValidatorRecorder) ValidateCronDescription(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "ValidateCronDescription", arg0)
}
