// Automatically generated by MockGen. DO NOT EDIT!
// Source: github.com/Jimdo/wonderland-crons/aws (interfaces: CronStore)

package mock

import (
	cron "github.com/Jimdo/wonderland-crons/cron"
	gomock "github.com/golang/mock/gomock"
)

// Mock of CronStore interface
type MockCronStore struct {
	ctrl     *gomock.Controller
	recorder *_MockCronStoreRecorder
}

// Recorder for MockCronStore (not exported)
type _MockCronStoreRecorder struct {
	mock *MockCronStore
}

func NewMockCronStore(ctrl *gomock.Controller) *MockCronStore {
	mock := &MockCronStore{ctrl: ctrl}
	mock.recorder = &_MockCronStoreRecorder{mock}
	return mock
}

func (_m *MockCronStore) EXPECT() *_MockCronStoreRecorder {
	return _m.recorder
}

func (_m *MockCronStore) Save(_param0 string, _param1 string, _param2 *cron.CronDescription) error {
	ret := _m.ctrl.Call(_m, "Save", _param0, _param1, _param2)
	ret0, _ := ret[0].(error)
	return ret0
}

func (_mr *_MockCronStoreRecorder) Save(arg0, arg1, arg2 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Save", arg0, arg1, arg2)
}
