// Automatically generated by MockGen. DO NOT EDIT!
// Source: github.com/Jimdo/wonderland-crons/aws (interfaces: CronStore)

package mock

import (
	cron "github.com/Jimdo/wonderland-crons/cron"
	gomock "github.com/golang/mock/gomock"
)

// Mock of CronStore interface
type MockCronStore struct {
	ctrl     *gomock.Controller
	recorder *_MockCronStoreRecorder
}

// Recorder for MockCronStore (not exported)
type _MockCronStoreRecorder struct {
	mock *MockCronStore
}

func NewMockCronStore(ctrl *gomock.Controller) *MockCronStore {
	mock := &MockCronStore{ctrl: ctrl}
	mock.recorder = &_MockCronStoreRecorder{mock}
	return mock
}

func (_m *MockCronStore) EXPECT() *_MockCronStoreRecorder {
	return _m.recorder
}

func (_m *MockCronStore) Delete(_param0 string) error {
	ret := _m.ctrl.Call(_m, "Delete", _param0)
	ret0, _ := ret[0].(error)
	return ret0
}

func (_mr *_MockCronStoreRecorder) Delete(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Delete", arg0)
}

func (_m *MockCronStore) GetResourceName(_param0 string) (string, error) {
	ret := _m.ctrl.Call(_m, "GetResourceName", _param0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockCronStoreRecorder) GetResourceName(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "GetResourceName", arg0)
}

func (_m *MockCronStore) List() ([]string, error) {
	ret := _m.ctrl.Call(_m, "List")
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockCronStoreRecorder) List() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "List")
}

func (_m *MockCronStore) Save(_param0 string, _param1 string, _param2 *cron.CronDescription, _param3 string) error {
	ret := _m.ctrl.Call(_m, "Save", _param0, _param1, _param2, _param3)
	ret0, _ := ret[0].(error)
	return ret0
}

func (_mr *_MockCronStoreRecorder) Save(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Save", arg0, arg1, arg2, arg3)
}

func (_m *MockCronStore) SetDeployStatus(_param0 string, _param1 string) error {
	ret := _m.ctrl.Call(_m, "SetDeployStatus", _param0, _param1)
	ret0, _ := ret[0].(error)
	return ret0
}

func (_mr *_MockCronStoreRecorder) SetDeployStatus(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "SetDeployStatus", arg0, arg1)
}
