// Automatically generated by MockGen. DO NOT EDIT!
// Source: github.com/Jimdo/wonderland-crons/aws (interfaces: RuleCronManager)

package mock

import (
	gomock "github.com/golang/mock/gomock"
)

// Mock of RuleCronManager interface
type MockRuleCronManager struct {
	ctrl     *gomock.Controller
	recorder *_MockRuleCronManagerRecorder
}

// Recorder for MockRuleCronManager (not exported)
type _MockRuleCronManagerRecorder struct {
	mock *MockRuleCronManager
}

func NewMockRuleCronManager(ctrl *gomock.Controller) *MockRuleCronManager {
	mock := &MockRuleCronManager{ctrl: ctrl}
	mock.recorder = &_MockRuleCronManagerRecorder{mock}
	return mock
}

func (_m *MockRuleCronManager) EXPECT() *_MockRuleCronManagerRecorder {
	return _m.recorder
}

func (_m *MockRuleCronManager) DeleteRule(_param0 string) error {
	ret := _m.ctrl.Call(_m, "DeleteRule", _param0)
	ret0, _ := ret[0].(error)
	return ret0
}

func (_mr *_MockRuleCronManagerRecorder) DeleteRule(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "DeleteRule", arg0)
}

func (_m *MockRuleCronManager) RunTaskDefinitionWithSchedule(_param0 string, _param1 string, _param2 string) error {
	ret := _m.ctrl.Call(_m, "RunTaskDefinitionWithSchedule", _param0, _param1, _param2)
	ret0, _ := ret[0].(error)
	return ret0
}

func (_mr *_MockRuleCronManagerRecorder) RunTaskDefinitionWithSchedule(arg0, arg1, arg2 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "RunTaskDefinitionWithSchedule", arg0, arg1, arg2)
}
