// Automatically generated by MockGen. DO NOT EDIT!
// Source: github.com/Jimdo/wonderland-crons/aws (interfaces: TaskDefinitionStore)

package mock

import (
	cron "github.com/Jimdo/wonderland-crons/cron"
	gomock "github.com/golang/mock/gomock"
)

// Mock of TaskDefinitionStore interface
type MockTaskDefinitionStore struct {
	ctrl     *gomock.Controller
	recorder *_MockTaskDefinitionStoreRecorder
}

// Recorder for MockTaskDefinitionStore (not exported)
type _MockTaskDefinitionStoreRecorder struct {
	mock *MockTaskDefinitionStore
}

func NewMockTaskDefinitionStore(ctrl *gomock.Controller) *MockTaskDefinitionStore {
	mock := &MockTaskDefinitionStore{ctrl: ctrl}
	mock.recorder = &_MockTaskDefinitionStoreRecorder{mock}
	return mock
}

func (_m *MockTaskDefinitionStore) EXPECT() *_MockTaskDefinitionStoreRecorder {
	return _m.recorder
}

func (_m *MockTaskDefinitionStore) AddRevisionFromCronDescription(_param0 string, _param1 *cron.CronDescription) (string, error) {
	ret := _m.ctrl.Call(_m, "AddRevisionFromCronDescription", _param0, _param1)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockTaskDefinitionStoreRecorder) AddRevisionFromCronDescription(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "AddRevisionFromCronDescription", arg0, arg1)
}

func (_m *MockTaskDefinitionStore) DeleteByFamily(_param0 string) error {
	ret := _m.ctrl.Call(_m, "DeleteByFamily", _param0)
	ret0, _ := ret[0].(error)
	return ret0
}

func (_mr *_MockTaskDefinitionStoreRecorder) DeleteByFamily(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "DeleteByFamily", arg0)
}
