#!/bin/sh
# Test driver used to test code inside Docker
# Note: Alpine has no /bin/bash
set -e

gometalinter.v1 --config metalinter-config.json ./... || true

packages=$(go list ./... | grep -v /vendor/)
echo $packages | xargs go test -tags=$TEST_TAGS -v
